version: "3"

services:
  gatekiosk-api:
    build: api/
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=vehicle-gate-kiosk.ca4lcabxs5eo.us-gov-west-1.rds.amazonaws.com
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=Vehiclekiosk45!
      - DB_NAME=vehicle_gate_kiosk
    volumes:
      - type: bind
        source: ./api/src
        target: /app/src
    command: npm run start
    restart: on-failure
